<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.witontek.com/ehospital/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="TicketPayWebServiceImplV2Service" targetNamespace="http://www.witontek.com/ehospital/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="unqualified" targetNamespace="http://www.witontek.com/ehospital/" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="createOrder" type="tns:createOrder" />
      <xs:element name="createOrderResponse" type="tns:createOrderResponse" />
      <xs:complexType name="createOrder">
        <xs:sequence>
          <xs:element minOccurs="0" form="qualified" name="inputStr" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="createOrderResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="return" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="createOrderResponse">
    <wsdl:part name="parameters" element="tns:createOrderResponse" />
  </wsdl:message>
  <wsdl:message name="createOrder">
    <wsdl:part name="parameters" element="tns:createOrder" />
  </wsdl:message>
  <wsdl:portType name="ITicketPayWebServiceV2">
    <wsdl:operation name="createOrder">
      <wsdl:input name="createOrder" message="tns:createOrder" />
      <wsdl:output name="createOrderResponse" message="tns:createOrderResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TicketPayWebServiceImplV2ServiceSoapBinding" type="tns:ITicketPayWebServiceV2">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="createOrder">
      <soap:operation soapAction="http://www.witontek.com/ehospital/createOrder" style="document" />
      <wsdl:input name="createOrder">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="createOrderResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TicketPayWebServiceImplV2Service">
    <wsdl:port name="TicketPayWebServiceImplV2Port" binding="tns:TicketPayWebServiceImplV2ServiceSoapBinding">
      <soap:address location="http://ehospital.witontek.com/eHospital2/services/ticketPayServiceV2" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>